#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-D-0 -d  VI VII VIII IX X

feh --bg-fill ~/.config/wallpaper/wall1.jpg ~/.config/wallpaper/wall2.jpg

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
